'********** Copyright 2016 Roku Corp.  All Rights Reserved. **********

sub Main()
  showChannelSGScreen()
end sub

sub showChannelSGScreen()
  screen = CreateObject("roSGScreen")
  m.port = CreateObject("roMessagePort")
  screen.setMessagePort(m.port)

  scene = screen.CreateScene("Home")
  screen.show()

  m.spSdk = new SourcepointSdk(22, "https://dan2.multicampaign.com", ["ccpa", "gdpr"])
  consent = m.spSdk.getUserConsent()

  print "consent object: "
  for each leg in consent
    print "-----"
    print leg
    print consent[leg]
  end for

  while(true)
    msg = wait(0, m.port)
    msgType = type(msg)

    if msgType = "roSGScreenEvent"
      if msg.isScreenClosed() then return
    end if
  end while

end sub
