'********** Copyright 2016 Roku Corp.  All Rights Reserved. **********

sub Main()
  showChannelSGScreen()
end sub

sub showChannelSGScreen()
  screen = CreateObject("roSGScreen")
  m.port = CreateObject("roMessagePort")
  screen.setMessagePort(m.port)

  scene = screen.CreateScene("Home")
  screen.show()

  scene.observeField("run_campaign_logic", m.port)
  scene.observeField("open_pm", m.port)

  m.spSdk = new SourcepointSdk(22, "https://dan2.multicampaign.com", {"ccpa": {}}, {}, false)

  runCampaign()

  while(true)
    msg = wait(0, m.port)
    msgType = type(msg)

    if msgType = "roSGScreenEvent"
      if msg.isScreenClosed() then return
    else if msgType = "roSGNodeEvent" then
      field = msg.getField()
      if field = "open_pm" then
        m.spSdk.openPrivacyManager("ccpa", 15995)
      else if field = "run_campaign_logic" then
        runCampaign()
      end if
    end if
  end while

end sub

sub runCampaign()
  consent = m.spSdk.runCampaignLogic()

  print "consent object: "
  for each leg in consent
    print "-----"
    print leg
    print consent[leg]
  end for
end sub
